// Common college majors list for dropdowns
export const MAJORS = [
  "Accounting",
  "Aerospace Engineering",
  "Agricultural Engineering",
  "Agricultural Sciences",
  "Anthropology",
  "Architecture",
  "Art History",
  "Biochemistry",
  "Bioengineering",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communication",
  "Computer Engineering",
  "Computer Science",
  "Criminal Justice",
  "Data Science",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Engineering",
  "Environmental Science",
  "Finance",
  "Food Science",
  "Graphic Design",
  "History",
  "Industrial Engineering",
  "Information Systems",
  "Journalism",
  "Kinesiology",
  "Marketing",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Music",
  "Nursing",
  "Nutrition",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Theatre",
  "Other",
] as const;

export type Major = typeof MAJORS[number];

